# Generated by Django 4.2.7 on 2025-07-26 05:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Influencer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Influencer's full name", max_length=255)),
                ('category', models.CharField(help_text='Influencer category (e.g., Fashion, Tech, Fitness)', max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], help_text="Influencer's gender", max_length=10)),
                ('follower_count', models.IntegerField(default=0, help_text='Number of followers')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('youtube', 'YouTube'), ('twitter', 'Twitter'), ('tiktok', 'TikTok'), ('linkedin', 'LinkedIn')], help_text='Primary platform', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Influencer',
                'verbose_name_plural': 'Influencers',
                'db_table': 'influencers',
                'ordering': ['-follower_count'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('youtube', 'YouTube'), ('twitter', 'Twitter'), ('tiktok', 'TikTok'), ('linkedin', 'LinkedIn')], help_text='Platform where post was made', max_length=20)),
                ('date', models.DateField(help_text='Date of the post')),
                ('url', models.URLField(blank=True, help_text='URL to the post', max_length=500, null=True)),
                ('caption', models.TextField(blank=True, help_text='Post caption or description', null=True)),
                ('reach', models.IntegerField(default=0, help_text='Number of people who saw the post')),
                ('likes', models.IntegerField(default=0, help_text='Number of likes')),
                ('comments', models.IntegerField(default=0, help_text='Number of comments')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('influencer', models.ForeignKey(help_text='Associated influencer', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='influencers.influencer')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'db_table': 'posts',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
