# Generated by Django 4.2.7 on 2025-07-26 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('influencers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(help_text='Data source (e.g., Google Analytics, Shopify)', max_length=100)),
                ('campaign', models.CharField(help_text='Campaign name or identifier', max_length=255)),
                ('user_id', models.CharField(help_text='User identifier from tracking system', max_length=255)),
                ('product', models.CharField(help_text='Product name or SKU', max_length=255)),
                ('date', models.DateField(help_text='Date of the tracking event')),
                ('orders', models.IntegerField(default=0, help_text='Number of orders')),
                ('revenue', models.DecimalField(decimal_places=2, default=0.0, help_text='Revenue generated', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('influencer', models.ForeignKey(help_text='Associated influencer', on_delete=django.db.models.deletion.CASCADE, related_name='tracking_data', to='influencers.influencer')),
            ],
            options={
                'verbose_name': 'Tracking Data',
                'verbose_name_plural': 'Tracking Data',
                'db_table': 'tracking_data',
                'ordering': ['-date', '-created_at'],
                'unique_together': {('user_id', 'date', 'product', 'influencer')},
            },
        ),
    ]
