# Generated by Django 4.2.7 on 2025-07-26 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingdata',
            name='brand',
            field=models.CharField(default='', help_text='Brand name', max_length=255),
        ),
    ]
